### ISSUE TITLE
Installation Error: Sidekiq 3.2.6 does not support Ruby 1.9

### ISSUE THREAD

**Issue by curi0usJack** [pentestgeek/phishing-frenzy#135]
This error occurs following both the "manual" installation steps as well as the docker installation steps. Operating System is clean install of Ubuntu Server 14.04 LTS

Not sure if this is a bug or something missing from the documentation.

![image](https://cloud.githubusercontent.com/assets/5608516/5655588/5c3510f6-9695-11e4-9b4b-2061002d6f60.png)

**Comment by zeknox** [comment]
Thanks for the feedback. This looks to be a problem with this version of sidekick not supporting ruby 1.9.  We will work towards updating the documentation to reflect this. In the meantime you can install a newer version of ruby to get up and running.

This should install latest stable version of rvm and ruby:
<pre>
$ \curl -sSL https://get.rvm.io | bash -s stable --ruby
</pre>

**Comment by b00stfr3ak** [comment]
I'll have to look at the docker version.  If the newer version  of Sidekiq doesn't support 1.9, I'll have to hard code an older version or see if Ubuntu has put ruby 2.0 in their repo.

**Comment by drag00n** [comment]
@b00stfr3ak you can also add the brightbox repo and install from there.

**Comment by curi0usJack** [comment]
I reverted to a clean install snapshot and tried everything again. I ended up getting it working. I think the problem was I was in the wrong directory when running the bundle sidekiq command. Not sure why I'd get the same error on the docker install, but who knows. ??

Additionally, here are a few proposed changes to the documentation.

1) Step #1: the apt-get install should read "apache2", not "apache"
2) Pull down the gpg keys prior to installing ruby: $gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
3) In the pf.conf file, need to comment out "RailsEnv development" until after passenger install script has run. Otherwise passenger install fails with :

AH00526: Syntax error on line 5 of /etc/apache2/pf.conf:
Invalid command 'RailsEnv', perhaps misspelled or defined by a module not included in the server configuration

and the apache configtest fails (with the same error). After installing passenger, uncomment the RailsEnv line and apache starts successfully.

Everything else worked well. I must have made a mistake somewhere along the way the first time through. Thanks for your timely response!

**Comment by efensive** [comment]
Of note, on Kali installs there are a lot of missing dependencies, e.g. I had to install:

apt-get install libcurl3 libidn11-dev librtmp-dev libssh2-1-dev

After, I had to apt-get -f install since things were really messy just to install: libcurl4-openssl-dev libcurl4-gnutls-dev prior to even building passenger-install-apache2-module. In order this is what I had to do:

curl -L https://get.rvm.io | bash -s stable --ruby
source /usr/local/scripts/rvm
source ~/.bashrc
rvm all do gem install --no-rdoc --no-ri passenger
apt-get install install apache2-threaded-dev
apt-get download libapr1-dev libaprutil-dev
dpkg -i libapr1-*
apt-get -f install 
dpkg -i libaprutil*
apt-get -f install
apt-get install libcurl3 libidn11-dev librtmp-dev libssh2-1-dev
apt-get -f install
apt-get download libcurl4-openssl-dev libcurl4-gnutls-dev (these would not build normally)
dpkg -i libcurl4-open* 
apt-get -f install
dpkg -i libcurl4-gn*
apt-get -f install
gem install passenger
passenger-install-apache2-module

Then came the sidekiq errors which I somewhere fixed by butchering more apt-get installs, rvm voodoo, after I got it working to a startable point, I had to: mkdir logs to run bundle exec sidekiq -C config/sidekiq.yml which for now is running with the following errors:

expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
warning: you are loading parser/ruby22 from /path/active_support/dependencies.rb:247:in `require'
warning: Ruby 2.2 is not released yet and parser support may be incomplete.

This came about after the suggested by zeknox: curl -sSL https://get.rvm.io | bash -s stable --ruby

**Comment by johnk3r** [comment]
Hello. I am also having the same problem.

I'm doing the installation by Docker. I'm using Ubuntu 14.04.1.
When I run the command:
"sudo docker build -t =" b00stfr3ak / ubuntu-phishingfrenzy "github.com/b00stfr3ak/ubuntu-phishingfrenzy"

I get the "Sidekiq 3.2.6 does not support Ruby 1.9" message. Some can help me?

**Comment by b00stfr3ak** [comment]
I've updated the repo and everything works now.  Let me know if you run into any issues.

https://github.com/b00stfr3ak/ubuntu-phishingfrenzy

**Comment by johnk3r** [comment]
Hi @b00stfr3ak !
The installation was successful! :) 

After installation ran the command: docker run -d -p 80:80 b00stfr3ak / ubuntu-phishingfrenzy ,  and accessed in the browser address http://127.0.0.1. Appears the Apache screen.

I've never used the Docker, how do I access the web console Phishing Frenzy ?

**Comment by zeknox** [comment]
Create an entry for phishingfrenzy.local in your hosts file that points to 127.0.0.1. This is required since you have defined this as the serverName in pf.conf file.

Brandon

**Comment by johnk3r** [comment]
Ok. I did not do any statement in pf.conf file and had already declared the address in the hosts file.

When access 127.0.0.1 still appears to apache screen. If the access phishingfrenzy.local address works.

I can edit the file apache2.conf?

**Comment by zeknox** [comment]
If you run `apachectl -S` you will see a list of configured virtual hosts which also should include phishingfrenzy.local. This command will also show you what configuration file this is coming from.  If you want to change it something else you will most likely configure `/etc/apache2/pf.conf`

**Comment by johnk3r** [comment]
I will do the installation for Ubuntu without using the Docker. This very giving many problems ... thanks.

**Comment by zeknox** [comment]
This is a problem with not running PF with a ruby 2.x version which is required for sidekiq. Here is what needs to be done if you have rvm installed.

List the installed ruby version
<pre>$ rvm list</pre>

Install ruby 2.1
<pre>$ rvm install 2.1</pre>

If you want to make 2.1 the default
<pre$ rvm use 2.1 --default></pre>

I'm closing this ticket. Get your ruby version up to date and this shouldn't be an issue.
