### ISSUE TITLE
Campaign e-mail issue

### ISSUE THREAD

**Issue by nerbix** [pentestgeek/phishing-frenzy#156]
When launching a campaign, I received an internal server error after 4 of 30 emails had been sent.  Is there any way to push out the other emails without re-launching and resending the first 4?

Could also be a feature request -- the ability to send or resend emails to specific targets.

**Comment by zeknox** [comment]
So I've heard of this happening and I think it's related to an unstable SMTP service IMO.  I use a paid for SMTP service and I'm able to send 1500 emails without one SMTP failure.

Anyways, onto the issue.  What you'll want to do is go into the victims page and see visually which victims have been sent to.  Then click "Delete All". This will remove all of the victims from the campaign, but still retain the stats for the victims it sent too.

Then what you'll want to do is re-add in all the emails it did not send too and click launch again.

**Comment by nerbix** [comment]
That method will retain reporting for those users who already received the email even if they submit creds a few days from now?

I re-launched using a 10 second SMTP delay and all 30 emails made it out just fine this time.  I'm using Office365 purchased through godaddy, just as a data point.

**Comment by zeknox** [comment]
Yes, it will retain the report for those users that it sent too. When you click the "Delete All" button PF will look at which victims have been sent to already, and if they have been sent to it will disable the victim instead of deleting it. This allows the stats to be retained for the duration of the campaign within the reports page.
