### ISSUE TITLE
How to track malicious attachment

### ISSUE THREAD

**Issue by agamotto1** [pentestgeek/phishing-frenzy#175]
I would like to test users not only on clicking links but clicking on malicious documents as well. I created a template and word doc that is simply launching a website but I don't see any way of tracking clicks on the attachment and emails.

**Comment by zeknox** [comment]
Please see this thread here for details:
https://github.com/pentestgeek/phishing-frenzy/issues/108

Brandon

**Comment by agamotto1** [comment]
Thank you

**Comment by zeknox** [comment]
The real challenge here is having PF dynamically generate a file attachment such as PDF, Word, etc...

If it was a simple ascii attachment such as HTML or something, this would be relatively easy because we could code PF to dynamically assign the UID within each HTML attachment.

Word or PDF would be incredibly challenging since it's not just an ascii format where you can inject the UID in somewhere.  Hope this helps.

**Comment by agamotto1** [comment]
I was able to create the word doc to launch the website. I am wondering if
I can just use the website index and format it as PHP then have PF point
directly to the website while it is being hosted on the same server as PF.

**Comment by zeknox** [comment]
Even tho you have the word doc opening the website, how are you injecting the UID into the word doc so you can correlate the word doc opening to a specific target?

You can get as creative as you like, just keep in mind nothing will be tracked unless you make the proper HTTP POST request while passing in the UID to tie it back to the target.
