### ISSUE TITLE
Site cloner

### ISSUE THREAD

**Issue by amzatoune** [pentestgeek/phishing-frenzy#230]
Something went wrong after I hit the Clone website button : 
production.log : 
[..]Direction\"};</script><script type=\"text/javascript\" src=\"https://www.pentestgeek.com/wp-content/cache/minify/000000/M9EvLM1Mzi5JTC_Wy83M0zHUTy5KrMzP0y2uzCtJrNDNyEzPyAHiktQi_dKSzBx9oErd1JTMkvwiqMr4whIA.js\"></script>\n</body>\n</html>\n', '200', '2015-09-09 20:43:14', 'http://www.pentestgeek.com')):
  app/controllers/clones_controller.rb:56:in `block in create'
  app/controllers/clones_controller.rb:55:in `create'

**Comment by amzatoune** [comment]
Apparently I can't edit enaything within the framework , similar errors found also when trying to edit the email template, or importing PFTemplates also !

**Comment by zeknox** [comment]
```
Permission denied @ rb_sysopen - /var/www/phishing-frenzy/public/uploads/attachment/file/3/intel.html.erb
```

The issue here is permission related.  If your going to be editing parts of the code you need to change the permissions back to a state where www-data has read write access still because Apache runs under the context of the www-data account.

Example of a commands you likely need to run when you edit files within the `phishing-frenzy` directory.
```
$ sudo chown -R www-data:www-data /var/www/phishing-frenzy/
```

```
$ sudo chmod -R 755 /var/www/phishing-frenzy/public/uploads/
```
