### ISSUE TITLE
CLEARING MAIL LOGS

### ISSUE THREAD

**Issue by amzatoune** [pentestgeek/phishing-frenzy#232]
how can I clear sidekiq data (Processed, failed nd so on ...) and also the recent blasts in the campaign menu !

**Comment by zeknox** [comment]
To clear all the sidekiq data you will need to navigate to the `rails console` and run the following command:
```
Sidekiq::Stats.new.reset
```

There currently is no way to clear the recent blasts within a campaign. This is indended by design to act as an audit trail of emails sent for the campaign.  If you're want to reset report stats you can do that within the reports page itself.

**Comment by amzatoune** [comment]
thanks man
