### ISSUE TITLE
Sidekiq, background email sending

### ISSUE THREAD

**Issue by amzatoune** [pentestgeek/phishing-frenzy#234]
Can one deliberately change the maximum parallel connections on the sidekiq background sending ?
It is by default set to 5 !

**Comment by zeknox** [comment]
Short answer is yes.  I have since updated the `master` branch to default to 25.  You need to make sure that whatever is configured for the `sidekiq.yml` is not larger than what is configured in `database.yml`.

Otherwise the database will get overrun with connections and fail when sending emails.  Also another thing to be careful of is overloading the SMTP service your sending through.
