### ISSUE TITLE
Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by dimpol** [pentestgeek/phishing-frenzy#282]
Hi i am a noob i admit it.

i receive this : 
![untitled](https://cloud.githubusercontent.com/assets/4255178/13814764/40652338-eb90-11e5-8349-95f01d81685d.png)

any clues to fix this?

**Comment by zeknox** [comment]
First make sure you have performed a bundle install in the application directory. If you have done that already then I believe you can simply add --deployment to your bundle install:
<pre>$ bundle install --deployment</pre>

Restart Apache and Test

**Comment by dimpol** [comment]
Nope i already tried --deployment.  
Maybe i did something wrong when i edited the sudoers file? i just added "www-data ALL=(ALL) NOPASSWD: /etc/init.d/apache2 reload" at the end of the file

**Comment by zeknox** [comment]
No I dont think that has anything to do with your issue here.  The issue looks like the application does not think you have the Gems installed, or what I believe could be happening is that the application is trying to use a different version of ruby which doesn't have the needed Gems installed.

The deployment flag has typically solved this issue in the past when I ran into it.

**Comment by dimpol** [comment]
OK thanks a lot. i will try to figure this out

**Comment by zeknox** [comment]
Sorry I'm not of more assistance here, but please keep us posted on a workaround solution.
