### ISSUE TITLE
apachectl restart crashes docker image

### ISSUE THREAD

**Issue by ad0nis** [pentestgeek/phishing-frenzy#289]
- Created a fresh install from the docker image.
- Configured phishing campaign.
- Launched Test.
- Clicked link in test email -> connection refused.
- Go back into PF UI, and mark the "Active" checkbox for the campaign. This generates an error upon trying to save the changes. (Sorry this is a bad bug report, but I didn't save that error message.)
- Use docker to get a shell on the PF image via 'docker exec -it $image_id bash
- 'apachectl restart' inside docker image, and the image crashes instantly. The same thing happens with 'service apache restart'

**Comment by magickangaroo** [comment]
Probably best to log this with the author of the docker image itself.  https://github.com/b00stfr3ak/ubuntu-phishingfrenzy  

FYI, service apache2 reload works fine, and so far reloads everything I needed.  I *think* its because 

https://github.com/b00stfr3ak/ubuntu-phishingfrenzy/blob/master/startup.sh  has apachectl -DFOREGROUND but i haven't played around with it.

**Comment by zeknox** [comment]
Docker image is not supported as stated in the install guide.
