### ISSUE TITLE
Problem adding new images to a template.

### ISSUE THREAD

**Issue by xcolacho** [pentestgeek/phishing-frenzy#292]
Hi, first of all my english isn't good enough, so sorry about that. Im trying to add new images to a existing template, but I don't know if I'm doing something wrong. I added new images in the template menu as image attachment, then I opened 
`/var/www/phishing-frenzy/public/uploads/attachment/file/1/hta_powershell.html.erb`
And use the same method to call the images like the existing ones:
`<%= image_tag attachments ['1.png'].url %>` 
then I go to the preview option in the campaing menu and they appeared perfectly, but when I send to an email with "test" option or "launch", when I open the email in "gmail"  the original images appeared but the new ones didn't. Although new images appear in the email for download or copy to Drive. 

Thanks.

**Comment by magickangaroo** [comment]
Hi, have you tried editing the templates through the web interface / gui? It sounds like your editing them on disk, and I'm not sure if PF will notice the change when sending mails.  It also sounds like your trying to replace the image, rather than add a new one, so instead of editing the template, maybe try replacing the image within the template settings?

**Comment by Meatballs1** [comment]
<%= image_tag attachments ['1.png'].url %>

no space between `attachments['1.png'].url`

**Comment by zeknox** [comment]
@Meatballs1 is correct, looks like the syntax was incorrect.  Please reopen if you still have issues.
