### ISSUE TITLE
Question (Phishing URL)

### ISSUE THREAD

**Issue by Ncoder1** [pentestgeek/phishing-frenzy#295]
Hi,

This is an amazing tool, of course. I'm very thrilled to work on this. But im stuck at understanding something basic. I have few queries regarding the phishing URL.

1. The phishing URL does not load even after i launch the campaign. It returns a 404 page not found error.

2. The phishing URL intel.domain.com provided by phishingfrenzy, does it actually host a page in the internet ? In general you buy a domain and then host a phishing page, do i still need to do it ?

**Comment by zeknox** [comment]
1) the 404 is expected behavior.  You must pass in a UID parameter to view the phishing sites. Please checkout the troubleshooting section for more details.

2) You must own a domain and point that A record to the public IP address of your PF instance. If the campaign is active and configured properly it will work as expected.

**Comment by zeknox** [comment]
Closing for now, please re-open if you still have issues.
