### ISSUE TITLE
Launched campaign overwrites the dashboard

### ISSUE THREAD

**Issue by bauldini** [pentestgeek/phishing-frenzy#323]
When I activate a campaign with the same FQDN as the dashboard, I am no longer able to access the dashboard. You can see the config I have in the images. 
![8-3-2016 4-26-49 pm](https://cloud.githubusercontent.com/assets/20802417/17380927/74033188-5997-11e6-9c27-86535dd4cda6.png)
![8-3-2016 4-26-00 pm](https://cloud.githubusercontent.com/assets/20802417/17380943/88f206d2-5997-11e6-8678-354c70fa2ed2.png)
![8-3-2016 4-26-30 pm](https://cloud.githubusercontent.com/assets/20802417/17380945/88f62294-5997-11e6-9447-2cdd93eb369a.png)

**Comment by zeknox** [comment]
This is expected behavior.  The FQDN from the PF interface must be different from the FQDN of the phishing website.  This is simply how Apache VirtualHosts works.  What's happening now is you have 2 defined VirtualHosts configured with the same primarykey (analogy) and it's simply going to serve up the one that was loaded first.

**Comment by bauldini** [comment]
Ok. But when I set them differently I am unable to track user clicks, or emails opened. Am I missing a setting somewhere?

**Comment by bauldini** [comment]
Any Recommendation on this?

**Comment by bauldini** [comment]
Figured this out. I needed to have the HTTP:// to the site URL in global settings.

**Comment by zeknox** [comment]
Yeah sorry for the delay here, you need to make sure the Site URL within the Global Settings matches that of your PF interface.  This is the URL that is used to send click metrics to the API that PF uses for tracking analytics.
