### ISSUE TITLE
PF Dashboard is 404 after activating campaign - EC2 server

### ISSUE THREAD

**Issue by Arb2025** [pentestgeek/phishing-frenzy#329]
Hi!
Awesome product. Works great when installed locally but I get some problems when installing on an Ubuntu amazon server.

Installation went well. After activating a new campaign, I get a 404 on the PF dashboard, though the phishing domain works (I can get to the template using the UID). 

I don't get the password though.

Attached:
- FQDN/Domain
  ![screen shot 2016-09-21 at 12 10 45 pm](https://cloud.githubusercontent.com/assets/19546724/18704927/aa688a92-7ff4-11e6-9a2d-72d51a238375.png)

-Apachectl -S after activation
![screen shot 2016-09-21 at 12 13 26 pm](https://cloud.githubusercontent.com/assets/19546724/18704980/de60fa96-7ff4-11e6-938b-329a1c202533.png)
- 404 page I get after clicking activation
  ![screen shot 2016-09-21 at 12 12 56 pm](https://cloud.githubusercontent.com/assets/19546724/18704952/c8e78b76-7ff4-11e6-866d-1c36de8c3447.png)

Note that I don't use a domain, but the direct IP to access the server.

Thanks!

**Comment by zeknox** [comment]
Restart apache, but it looks like your Phishing Frenzy UI should be live on the FQDN of phishingfrenzy.com, you likely need to edit your hosts file to point this domain to the PF IP address or configure DNS to point the FQDN to the IP.

the PF UI is setup with Named VirtualHosts and it works best when you use a FQDN vs and IP.

**Comment by Arb2025** [comment]
Hi! Thanks for the answer.

I can get PF UI, until I activate a new campaign.
Then I get the 404 when trying to reach the UI

**Comment by JoRoi** [comment]
Hey Zeknox (and everyone else),

Having the same issue here:
Once activating the campaign, I get the 404 page.
If I remove the campaign's configuration file (i.e. "2.conf") and restart the server, I can load PF UI and even launch a campaign (send phishing emails).
In order to be able to receive statistics and username and passwords, I must restore the campaign's configuration file to its place and everything works.

So...
Please help me, there's seems to be a problem every time I activate a campaign and a configuration file is generated ("2.conf").
There seems to be a conflict between PF UI and the phishing site ("intel.domain.com"). 
What should I do in order to overcome this problem?

Thank you very much!

**Comment by JoRoi** [comment]
Guys, any ideas? 
Would highly appreciate any help I can get here...
Thanks!

**Comment by zeknox** [comment]
The 404 is expected behavior for all phishing sites.  You must pass in the parameter of UID in order for the phishing site to be displayed.

Additionally, you need to make sure your PF UI FQDN is different from the FQDN of your phishing site.

**Comment by JoRoi** [comment]
No no no...
I'm talking about the PF UI which gets the 404 page NOT the phishing sites...
The phishing sites work ok. After activation the UI of the PF is going down with 404 page. 

I'm using two different FQDN: one for the UI and another for the phishing site.
Personally I think that the problem is somewhere in the ports zone... there's some sort of collision there but I'm sure what it is.

Don't know what's wrong and how to solve it.

Any ideas... Do you need any further info from my end?
Thanks!

**Comment by JoRoi** [comment]
Zeknox, any kind of assistance would be great.
Can you help out here please?

Thanks!

**Comment by zeknox** [comment]
Can you show me the results of apachectl -S, want to see how the VirtualHosts are configured.  This feels like your trying to access the PF interface via an IP when it works best with a FQDN.

**Comment by JoRoi** [comment]
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server euroxyz.com (/etc/apache2/sites-enabled/1.conf:2)
         port 80 namevhost euroxyz.com (/etc/apache2/sites-enabled/1.conf:2)
                 alias euroxyz.com
         port 80 namevhost euroabc.com (/etc/apache2/pf.conf:1)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex default: dir="/var/lock/apache2" mechanism=fcntl 
Mutex mpm-accept: using_defaults
Mutex watchdog-callback: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used

==============================================

- currently, I can't load the PF UI and having a 404 page. 
- both euroxyz.com and euroabc.com are resolved at a public DNS to the same server ip.

Thanks a lot!

**Comment by zeknox** [comment]
Based on the info above, the PF interface should be live on euroabc.com FQDN.  If its not, ensure Apache is restarted so it's loading in this latest config.  Additionally, tail your apache logs to find out more info.

If your getting a 404 it may be that some other VHOST is getting triggered instead, the logs might enlighten you on the issue.

**Comment by JoRoi** [comment]
Hi,

Apache was restarted with `sudo service apache2 restart` and nothing changed.

Then I monitored both:
- /var/log/apache2$ tail -f error.log
- /var/log/apache2$ tail -f other_vhosts_access.log

but nothing popped up in the logs when I tried to reload euroabc.com

Anything else I need to try?
What am I missing here?

:(

**Comment by zeknox** [comment]
Try a separate domain for your PF UI, and a separate domain for the phishing site should solve the issue.
