### ISSUE TITLE
Add new Admin user 

### ISSUE THREAD

**Issue by vidaria** [pentestgeek/phishing-frenzy#367]
Please I am trying to add another admin user or just any user under manage user in Manage Users tab but the option i got is limited like  cant create any new user.  The only user I have is admin the default user but I want to add on another user to this tab so we dont have to all use just admin user but can use its own account to manage our  phishing.

The  only available tab in my web browser is manage account and when I click on it, it just allow me to edit the current Admin account.  Is there anyway i can add on more user account pls.

**Comment by zeknox** [comment]
This behavior is be design.  New users are able to register on the initial log in page when not authenticated to the application.  This way a new user can register for themselves, but must be approved by an existing admin. This was by design so the admin did not have direct knowledge of the password a user registers with.  Cheers.

**Comment by vidaria** [comment]
Thank you very much Brandon much appreciated the helps.  Got it done with your instructions.

Thank you so much.
